---
title: "Testing of BEST-COST R package"
author: "Alberto Castro & Axel Luyten"
output: html_document
---

# Goal
 
Install the healthiar package

# Install healthiar from GitHub

## Using keyring package

```{r eval=FALSE, include=FALSE}

# Store your pat using keyring::key_set()
## Only has to be done once
## Run this command and paste your GitHub PAT in the "Password" window that opens
# keyring::key_set("GITHUB_PAT_HEALTHIAR")

remotes::install_github(
  repo = "best-cost/best-cost_WPs",
  subdir = "/r_package/healthiar",
  ref = "HEAD", # By default "HEAD"; name of branch to install package from as a string
  force = TRUE,
  # auth_token = "", # Paste your GitHub PAT between the quotation marks
  auth_token = keyring::key_get("GITHUB_PAT_HEALTHIAR"),
  # dependencies = TRUE,
  build_vignettes = TRUE,
  # upgrade = c("always") # Update packages
  upgrade = c("never") # Never update packages
)

```

## Using credentials package

```{r Install {healthiar} from GitHub, eval=FALSE, include=FALSE}

## NOTE: if an older version of {healthiar} already installed and loaded, detach first 
# detach("package:healthiar", unload = TRUE) # Throws error if package was not loaded

## Option A: Using remotes package (size: 426 KB)
### Advantage: no installation of Git required
# credentials::set_github_pat() # paste github PAT if prompted
# ?remotes::install_github
remotes::install_github(
  repo = "best-cost/best-cost_WPs",
  subdir = "/r_package/healthiar",
  ref = "HEAD", # By default "HEAD"; name of branch to install package from as a string
  force = TRUE,
  # auth_token = "", # Paste your GitHub PAT between the quotation marks
  # dependencies = TRUE,
  # build_vignettes = TRUE,
  build_vignettes = FALSE,
  # upgrade = c("always") # Update packages
  upgrade = c("never") # Never update packages
)

library(healthiar)

```


# Build & install healthiar from local source

```{r Install healthiar from local source, eval=FALSE, include=FALSE}

## NOTE: if an older version of {healthiar} already installed and loaded, detach first 
# detach("package:healthiar", unload = TRUE) # Throws error if package was not loaded

## Install package from .zip file
# devtools::build(binary = TRUE, path = "../testing/Workshops_and_demos/2025_04_10_UBD_policy") # Save current state of package as .zip file (e.g. to directly test changes in functions)
# install.packages("../testing/input/healthiar_0.0.0.1.zip", repos=NULL, type='source') # Modify file path

## Install package from .tar.gz file
# devtools::build(path = "../testing/input/") # Save current state of package as tar.gz file (e.g. to directly test changes in functions)
# install.packages("../testing/input/healthiar_0.0.0.1.tar.gz", repos=NULL, type='source') # Modify file path

# library(healthiar)
```


